### ISSUE TITLE
Point cloud update when cropping?

### ISSUE THREAD

**Issue by carlosjoserg** [Tabjones/pacman_vision#3]
The `scene_processed` (btw, in english would `processed_scene`) is not being updated when cropping is true. Looks like the message is latched there, and the cloud is not cleared somehow. It is weird, because I don't see the cloud actually.

I'm trying octomap (to not collide with the unkwon object), and this is without cropping (sometimes I put my hand in the middle of the scene, and it gets cleared after a while):

![not_cropping](https://dl.dropboxusercontent.com/u/16526900/notCropped.png)

And this is with cropping, I passed my hand, and after 5 min, it hasn't been cleared:

![cropping](https://dl.dropboxusercontent.com/u/16526900/cropping.png)

In fact, I `rostopic pub echo /pacman_vision/scene_processed`, and get some noisy data:

```
header: 
  seq: 28147
  stamp: 
    secs: 1455441327
    nsecs: 620173000
  frame_id: camera_rgb_optical_frame
height: 1
width: 3
fields: 
  - 
    name: x
    offset: 0
    datatype: 7
    count: 1
  - 
    name: y
    offset: 4
    datatype: 7
    count: 1
  - 
    name: z
    offset: 8
    datatype: 7
    count: 1
  - 
    name: rgb
    offset: 16
    datatype: 7
    count: 1
is_bigendian: False
point_step: 32
row_step: 96
data: [169, 132, 53, 62, 209, 175, 105, 61, 149, 193, 38, 63, 0, 0, 128, 63, 54, 49, 61, 0, 220, 127, 0, 0, 235, 21, 125, 116, 220, 127, 0, 0, 145, 166, 57, 62, 121, 128, 101, 61, 122, 233, 38, 63, 0, 0, 128, 63, 72, 65, 79, 0, 220, 127, 0, 0, 235, 21, 125, 116, 220, 127, 0, 0, 234, 255, 52, 62, 48, 105, 122, 61, 122, 233, 38, 63, 0, 0, 128, 63, 109, 99, 116, 0, 220, 127, 0, 0, 235, 21, 125, 116, 220, 127, 0, 0]
is_dense: True
```

---

Did you know that moveit already has the self-mask for point clouds... and with geometry scaling? However not dynamic configurable...
